#!/bin/bash

# Tests ParAd on a given matrix and prints benchmarks
# Parameters:
# $1 - matrix, $2 - agg

# direct solution
echo '=====' matrix: $1, keys: -a $2
mpirun -n 4 ./ParAd -c -r zsolve -a $2 -d 2 $1 output/${1}.sol

# check whether they are solutions
# multiply the system matrix by basis

# multiply system by basis
if [ -z "$3" ]; then
 ../utils/mul2m output/${1}.sol ${1} output/${1}.sol.res
else
 ../utils/transpose output/${1}.sol output/${1}.sol.trs
 ../utils/mul2m ${1} output/${1}.sol.trs output/${1}.sol.res
fi
# the file is empty if the multiplication result is zero
if [ -s output/${1}.sol.res ]; then 
  echo '***** ERROR:' output/${1}.sol is not a basis
  en=$((en+1))
else 
  echo '=====' output/${1}.sol is a basis
fi 
echo ""

# end

