#!/bin/sh
#SBATCH --time=10:00:00

# Tests ParAd on a given matrix and prints benchmarks
# Parameters:
# $1 - matrix

#start example: sbatch -N 11 -w "d[00-10]" -o output/test4_agg_slurm.stdout test4_agg_slurm tcp.spm

# Variables: r - solver, n - number of processes, en - error counter
r=zsolve
n=4
en=0

#set -o xtrace

# direct solution
echo '=====' matrix: $1, keys:
srun -N 1 ./ParAd -r zsolve -d 2 $1 output/${1}.sol

# check whether they are solutions
# multiply the system matrix by basis

# multiply system by basis
if [ -z "$3" ]; then
 ../utils/mul2m output/${1}.sol ${1} output/${1}.sol.res
else
 ../utils/transpose output/${1}.sol output/${1}.sol.trs
 ../utils/mul2m ${1} output/${1}.sol.trs output/${1}.sol.res
fi
# the file is empty if the multiplication result is zero
if [ -s output/${1}.sol.res ]; then 
  echo '***** ERROR:' output/${1}.sol is not a basis
  en=$((en+1))
else 
  echo '=====' output/${1}.sol is a basis
fi 
echo ""

# composition
echo '=====' matrix: $1, keys: -c
srun -N $n ./ParAd -c -r zsolve -d 2 $1 output/${1}.sol-c

# check whether they are solutions
# multiply the system matrix by basis

# multiply system by basis
if [ -z "$3" ]; then
 ../utils/mul2m output/${1}.sol-c ${1} output/${1}.sol-c.res
else
 ../utils/transpose output/${1}.sol-c output/${1}.sol-c.trs
 ../utils/mul2m ${1} output/${1}.sol-c.trs output/${1}.sol-c.res
fi
# the file is empty if the multiplication result is zero
if [ -s output/${1}.sol-c.res ]; then 
  echo '***** ERROR:' output/${1}.sol-c is not a basis
  en=$((en+1))
else 
  echo '=====' output/${1}.sol-c is a basis
fi 
echo ""

# METIS
echo '=====' matrix: $1, keys: -c -a 1
srun -N $n ./ParAd -c -r zsolve -a 1 -d 2 $1 output/${1}.sol-a1

# check whether they are solutions
# multiply the system matrix by basis

# multiply system by basis
if [ -z "$3" ]; then
 ../utils/mul2m output/${1}.sol-a1 ${1} output/${1}.sol-a1.res
else
 ../utils/transpose output/${1}.sol-a1 output/${1}.sol-a1.trs
 ../utils/mul2m ${1} output/${1}.sol-a1.trs output/${1}.sol-a1.res
fi
# the file is empty if the multiplication result is zero
if [ -s output/${1}.sol-a1.res ]; then 
  echo '***** ERROR:' output/${1}.sol-a1 is not a basis
  en=$((en+1))
else 
  echo '=====' output/${1}.sol-a1 is a basis
fi 
echo ""

# bin packing
echo '=====' matrix: $1, keys: -a -0.99
srun -N 16 ./ParAd -c -r zsolve -a -0.99 -d 2 $1 output/${1}.sol-a-1

# check whether they are solutions
# multiply the system matrix by basis

# multiply system by basis
if [ -z "$3" ]; then
 ../utils/mul2m output/${1}.sol-a-1 ${1} output/${1}.sol-a-1.res
else
 ../utils/transpose output/${1}.sol-a-1 output/${1}.sol-a-1.trs
 ../utils/mul2m ${1} output/${1}.sol-a-1.trs output/${1}.sol-a-1.res
fi
# the file is empty if the multiplication result is zero
if [ -s output/${1}.sol-a-1.res ]; then 
  echo '***** ERROR:' output/${1}.sol-a-1 is not a basis
  en=$((en+1))
else 
  echo '=====' output/${1}.sol-a-1 is a basis
fi 
echo ""

exit $en


# end

