#!/bin/bash

en=0

# Tests ParAd on chosen matrices

./test1_mpi tcp.spm ParTou
en=$((en+$?))
./test1_mpi bgp.spm ParTou -T
en=$((en+$?))
./test1_mpi AirplaneLD-pt-0200.spm ParTou
en=$((en+$?))
./test1_mpi AirplaneLD-pt-0200.spm zsolve
en=$((en+$?))

# generate clan

echo ***** generate matrix: gen_clans 9 100 spm 0.6 1.2 > c9-100.spm
../utils/gen_clans 9 100 spm 0.6 1.2 > c9-100.spm

# try generated clan

./test1_mpi c9-100.spm zsolve
en=$((en+$?))

if [ "$en" -gt "0" ]
then
  echo '*******************************************************************'
  echo "         ERRORS: $en times a wrong basis has been obtained" 
  echo '*******************************************************************'
else
  echo "All the tests completed successfully!"
fi
echo ""

# end

