#!/bin/bash

# tests ParAd on all .spm files and compares basises obtained via different methods
# please mind that it requires much time

en=0

for f in `ls *.spm`;
do
	echo matrix $f
#	./test1_mpi $f ParTou
#        en=$((en+$?))
	./test1_mpi $f zsolve
        en=$((en+$?))
#	./test1_mpi $f ParTou -T
#        en=$((en+$?))
	./test1_mpi $f zsolve -T
        en=$((en+$?))
done

if [ "$en" -gt "0" ]
then
  echo '*******************************************************************'
  echo "         ERRORS: $en times a wrong basis has been obtained" 
  echo '*******************************************************************'
else
  echo "All the tests completed successfully!"
fi
echo ""

# end

