#!/bin/sh
#SBATCH --time=10:00:00

# Tests ParAd on a series of matrices and prints benchmarks

#start example: sbatch -N 11 -w "d[00-11]" -o output/test4_agg_slurm_list.stdout test4_agg_slurm_list

#set -o xtrace

for m in AirplaneLD-pt-1000.spm afcs_48_b.spm deploy_7_b.spm dlcro_13_b.spm ht_d4k3p2b08.spm shared_memory-pt-50.spm;
do

	./test1_agg_slurm $1
	en=$((en+$?))


done

if [ "$en" -gt "0" ]
then
  echo '*******************************************************************'
  echo "         ERRORS: $en times a wrong basis has been obtained" 
  echo '*******************************************************************'
else
  echo "All the tests completed successfully!"
fi
echo ""

# end

# end

